### ISSUE TITLE
incorrect map element type: attribute "ingress": attributes "target_port" and "traffic_weight" are required

### ISSUE THREAD

**Issue by DzianisMatveyeu** [Azure/terraform-azure-container-apps#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

 v1.3.4

### Module Version

v0.2.0

### AzureRM Provider Version

v3.75.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app.container_app

### Terraform Configuration Files

```hcl
module "container-apps" {
  source  = "Azure/container-apps/azure"
  version = "0.2.0"
  # insert the 5 required variables here
  container_apps                                           = var.container_apps
  container_app_environment_name                           = var.container_app_environment_name
  location                                                 = var.location
  log_analytics_workspace_name                             = var.log_analytics_workspace_name
  resource_group_name                                      = "testrsg"
  container_app_secrets                                    = var.container_app_secrets
}
```

### tfvars variables values

```hcl
container_app_environment_name = "dev1"
log_analytics_workspace_name   = "dev1"
resource_group_name            = "dev1"
location                       = "eastus2"
container_apps = {
  test = {
    name          = "nginx"
    revision_mode = "Multiple"
    template = {
      containers = [{
        name         = "nginx"
        image        = "nginx:latest"
        cpu          = ".25"
        memory       = "0.5Gi"
        max_replicas = 2
        min_replicas = 1
        liveness_probe = {
          port      = 80
          transport = "HTTP"
        }
        readiness_probe = {
          port      = 80
          transport = "HTTP"
        }
        startup_probe = {
          port      = 80
          transport = "HTTP"
        }
      }]
      ingress = {
        target_port    = 80  
        traffic_weight = {
          percentage = 50  
        }
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Invalid value for input variable
│
│   on main.tf line 5, in module "container-apps":
│    5:   container_apps                                           = var.container_apps
│
│ The given value is not suitable for module.container-apps.var.container_apps declared at .terraform\modules\container-apps\variables.tf:7,1-26: incorrect map element type: attribute "ingress": attributes "target_port" and  
│ "traffic_weight" are required.
╵
╷
│ Error: Missing required argument
│
│   with module.container-apps.azurerm_container_app_environment.container_env,
│   on .terraform\modules\container-apps\main.tf line 25, in resource "azurerm_container_app_environment" "container_env":
│   25:   internal_load_balancer_enabled = var.container_app_environment_internal_load_balancer_enabled
│
│ "internal_load_balancer_enabled": all of `infrastructure_subnet_id,internal_load_balancer_enabled` must be specified
```

### Expected Behaviour

I expected that it would be easy to run a container app with this module.
In docs only 5 required variables. Documentation is not clear. 

### Actual Behaviour

I had more than 5 required and errors

**Comment by lonegunmanb** [comment]
Hi @DzianisMatveyeu thanks for reporting this issue to us. I've checked the [`template`](https://github.com/Azure/terraform-azure-container-apps/blob/main/variables.tf#L13-L81) object in this module's variable, the `ingress` object is not part of it, but in your tfvars it looks like you've declared `ingress` inside the `template` object, which might cause the error.

As for the following `Missing required argument` error, I've seen the same error in the e2e test, and I'm investigating it.

**Comment by zioproto** [comment]
@lonegunmanb could you please check if this is related to this provider issue ?

https://github.com/hashicorp/terraform-provider-azurerm/issues/20435#issuecomment-1777789144

The problem here is in this code:
https://github.com/Azure/terraform-azure-container-apps/blob/16332f4b8659ac7f9a1b4a62712575af1daca1ac/main.tf#L218-L229

It is probably enough to workaround the issue doing:

```
ingress = {
        target_port    = 80  
        traffic_weight = {
          percentage = 100  
          latestRevision = true
        }
      }
```

Without `latestRevision` with a valid value it will not work.

**Comment by lonegunmanb** [comment]
I'm closing this issue since this is a provider side issue according to [this comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/20435#issuecomment-2350895460) and has been fixed in [this pr](https://github.com/hashicorp/terraform-provider-azurerm/pull/27396). I've double checked the current variable's [type schema](https://github.com/Azure/terraform-azure-container-apps/blob/v0.4.0/variables.tf#L106-L111) and it is in sync with the [provider's schema](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.117.0/internal/services/containerapps/helpers/container_apps.go#L543-L579). Please feel free to reopen it if you have different thought @DzianisMatveyeu , thanks for your contribution!
